# Generated by Django 5.1 on 2025-06-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_type',
            field=models.CharField(blank=True, help_text='Device type (mobile, web, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, help_text='Firebase Cloud Messaging token', null=True),
        ),
    ]
