# Generated by Django 5.1 on 2025-07-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_device_type_user_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fcm_token',
        ),
    ]
