# Generated by Django 5.1.4 on 2025-01-23 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OperationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('original_image', models.ImageField(upload_to='operation_images/original/')),
                ('operated_image', models.ImageField(blank=True, null=True, upload_to='operation_images/operated/')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='operation.operation')),
            ],
        ),
        migrations.CreateModel(
            name='OperationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_description', models.TextField()),
                ('damage_type', models.CharField(max_length=100)),
                ('operation_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='operation.operationimage')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='RECEIVED', max_length=20)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='operation.operation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
